//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYTIEC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConnectionEFDataFirst : DbContext
    {
        public ConnectionEFDataFirst()
            : base("name=ConnectionEFDataFirst")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SYS_CONFIG> SYS_CONFIG { get; set; }
        public virtual DbSet<SYS_FUNCTION> SYS_FUNCTION { get; set; }
        public virtual DbSet<SYS_PARTY_TYPE> SYS_PARTY_TYPE { get; set; }
        public virtual DbSet<SYS_USER> SYS_USER { get; set; }
        public virtual DbSet<TBL_DEPARTMENT> TBL_DEPARTMENT { get; set; }
        public virtual DbSet<TBL_EMPLOYEE> TBL_EMPLOYEE { get; set; }
        public virtual DbSet<TBL_FAST_PAYROLL> TBL_FAST_PAYROLL { get; set; }
        public virtual DbSet<TBL_GROUP_MENU> TBL_GROUP_MENU { get; set; }
        public virtual DbSet<TBL_MATERIAL> TBL_MATERIAL { get; set; }
        public virtual DbSet<TBL_MATERIAL_GROUP> TBL_MATERIAL_GROUP { get; set; }
        public virtual DbSet<TBL_PARTY> TBL_PARTY { get; set; }
        public virtual DbSet<TBL_PARTY_OTHER_AMOUNT> TBL_PARTY_OTHER_AMOUNT { get; set; }
        public virtual DbSet<TBL_PARTY_PRODUCT> TBL_PARTY_PRODUCT { get; set; }
        public virtual DbSet<TBL_PARTY_PRODUCT_MATERIAL> TBL_PARTY_PRODUCT_MATERIAL { get; set; }
        public virtual DbSet<TBL_PARTY_SERVICE> TBL_PARTY_SERVICE { get; set; }
        public virtual DbSet<TBL_POSITION> TBL_POSITION { get; set; }
        public virtual DbSet<TBL_PRICE_PAYROLL> TBL_PRICE_PAYROLL { get; set; }
        public virtual DbSet<TBL_PRODUCT> TBL_PRODUCT { get; set; }
        public virtual DbSet<TBL_PRODUCT_GROUP> TBL_PRODUCT_GROUP { get; set; }
        public virtual DbSet<TBL_PRODUCT_MATERIAL> TBL_PRODUCT_MATERIAL { get; set; }
        public virtual DbSet<TBL_RECEIPT> TBL_RECEIPT { get; set; }
        public virtual DbSet<TBL_RESULT_ATT> TBL_RESULT_ATT { get; set; }
        public virtual DbSet<TBL_SERVICE> TBL_SERVICE { get; set; }
        public virtual DbSet<TBL_UOM> TBL_UOM { get; set; }
        public virtual DbSet<TBL_VENDOR> TBL_VENDOR { get; set; }
    }
}
