//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYTIEC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PRODUCT
    {
        public int ProductID { get; set; }
        public Nullable<int> GroupMenuID { get; set; }
        public Nullable<int> MaterialGroupID { get; set; }
        public Nullable<int> ProductGroupID { get; set; }
        public string ProductName { get; set; }
        public string Notes { get; set; }
        public decimal CostAmount { get; set; }
        public decimal ProfitAmount { get; set; }
        public decimal TotalAmount { get; set; }
        public bool IsActive { get; set; }
    }
}
