//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYTIEC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PRODUCT_GROUP
    {
        public int ProductGroupID { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> LevelID { get; set; }
    }
}
