//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYTIEC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SERVICE
    {
        public int ServiceID { get; set; }
        public string ServiceName { get; set; }
        public decimal UnitPrice { get; set; }
        public string Notes { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> UOMID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public bool IsStandard { get; set; }
    }
}
