//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYTIEC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PARTY
    {
        public int PartyID { get; set; }
        public System.DateTime BookingDate { get; set; }
        public System.DateTime PartyDate { get; set; }
        public System.DateTime NegativeDate { get; set; }
        public string CustomerName { get; set; }
        public string PhoneNumber1 { get; set; }
        public string PhoneNumber2 { get; set; }
        public string Address { get; set; }
        public string PartyAddress { get; set; }
        public Nullable<int> PartyTypeID { get; set; }
        public int NumberTablePlan { get; set; }
        public int NumberTableException { get; set; }
        public int NumberTableReal { get; set; }
        public int NumberTableVegetarian { get; set; }
        public decimal PriceVegetarian { get; set; }
        public decimal PricePerTablePlan { get; set; }
        public decimal PricePerTableReal { get; set; }
        public decimal DepositAmount { get; set; }
        public Nullable<System.DateTime> DepositDate { get; set; }
        public decimal OtherAmount { get; set; }
        public bool IsPayCashAfterDoneParty { get; set; }
        public bool IsPayBank { get; set; }
        public bool IsVAT { get; set; }
        public string Notes { get; set; }
        public Nullable<int> UserCreate { get; set; }
        public bool IsComplete { get; set; }
        public bool IsPayment { get; set; }
        public bool IsHidePricePlan { get; set; }
        public bool IsHidePriceReal { get; set; }
        public string NotesOtherAmount { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public string EmployeeReceipt { get; set; }
        public decimal VATPercent { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal TotalAmountAfterDeposit { get; set; }
        public decimal PayAmount { get; set; }
        public decimal RemainAmount { get; set; }
    }
}
