//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYTIEC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PARTY_PRODUCT_MATERIAL
    {
        public int ID { get; set; }
        public int PartyProductID { get; set; }
        public int PartyID { get; set; }
        public int ProductID { get; set; }
        public int MaterialID { get; set; }
        public decimal Quantity { get; set; }
        public int UnitPrice { get; set; }
        public decimal TotalAmount { get; set; }
        public Nullable<int> VendorID { get; set; }
        public bool IsDelivery { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Notes { get; set; }
    }
}
