//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYTIEC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EMPLOYEE
    {
        public int EmployeeID { get; set; }
        public string FullName { get; set; }
        public string IDCardNo { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public bool IsCalculatePayroll { get; set; }
        public bool IsCalAttendance { get; set; }
        public bool IsLeaveOff { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public string ACNo { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public bool IsPayByHour { get; set; }
        public int BasicSalary { get; set; }
        public string Notes { get; set; }
    }
}
