//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYTIEC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PRICE_PAYROLL
    {
        public int PriceID { get; set; }
        public System.DateTime TimeFrom { get; set; }
        public System.DateTime TimeTo { get; set; }
        public int UnitPrice { get; set; }
    }
}
